"""Turns results/*.json into RESULTS.md with a permalink for every finding."""
import collections
import json
import pathlib

here = pathlib.Path(__file__).parent
repos = [
    line.split()
    for line in (here / "repos.txt").read_text().splitlines()
    if line.strip() and not line.startswith("#")
]

rows, details = [], []
all_keys = collections.Counter()
all_verdicts = collections.Counter()
totals = collections.Counter()

for repo, commit in repos:
    data = json.loads((here / "results" / f"{repo.replace('/', '_')}.json").read_text())
    files = data.get("files") or []
    code_files = {
        f["path"]
        for f in files
        for x in f["findings"]
        if x.get("forms") != ["comment"]
    }
    rows.append(
        f"| [{repo}](https://github.com/{repo}/tree/{commit}) | `{commit}` | {data['filesWalked']} | "
        f"{data['filesScanned']} | {data['deprecatedUsages']} | {data.get('deprecatedInComments', 0)} | {len(code_files)} |"
    )
    for k in ("filesWalked", "filesScanned", "deprecatedUsages", "deprecatedInComments"):
        totals[k] += data.get(k, 0)
    totals["files"] += len(code_files)

    lines = []
    for f in files:
        path = f["path"].removeprefix("./")
        for x in f["findings"]:
            where = "comment" if x.get("forms") == ["comment"] else "code"
            for ln in x["lines"]:
                if where == "code":
                    all_keys[x["key"]] += 1
                    all_verdicts[x["verdict"]] += 1
                to = x.get("replacement") or x.get("replacementReason", "")
                lines.append(
                    f"| [{path}:{ln}](https://github.com/{repo}/blob/{commit}/{path}#L{ln}) | "
                    f"`{x['key']}` | {x['verdict']} | {to} | {where} |"
                )
    if lines:
        details.append(f"### {repo}\n\n| Location | Key | Verdict | Use instead | Where |\n| --- | --- | --- | --- | --- |\n" + "\n".join(lines))

print("# Real-world scan results\n")
print(
    "Generated by `bench/run.sh`: the Go CLI scanned each repository at the pinned commit. "
    "Every verdict comes from the Sanity dataset through Sanity Context, against spec v1.44.0.\n"
)
print("| Repository | Commit | Files walked | Files mentioning attributes | Deprecated usages in code | In comments | Files to touch |")
print("| --- | --- | --- | --- | --- | --- | --- |")
print("\n".join(rows))
print(
    f"| **Total** | | {totals['filesWalked']} | {totals['filesScanned']} | **{totals['deprecatedUsages']}** | "
    f"{totals['deprecatedInComments']} | {totals['files']} |\n"
)
print("**By verdict (code only):** " + ", ".join(f"{k} {v}" for k, v in all_verdicts.most_common()) + "\n")
print("**Most common retired keys:** " + ", ".join(f"`{k}` {v}" for k, v in all_keys.most_common(10)) + "\n")
print(
    "A finding means the key is deprecated in the spec. It does not always mean the code is wrong: "
    "test fixtures that read old data, or libraries that dual-emit on purpose during a migration, "
    "should keep the old key for now. The table links every line so each one can be checked.\n"
)
print("\n\n".join(details))
